In [2]:
import numpy as np
import pyaudio
import time
from pyldpc import make_ldpc, encode, decode, get_message

# Ses kayıt parametreleri
CHUNK = 512* 1
FORMAT = pyaudio.paInt16
CHANNELS = 1
RATE = 44100

# Taşıyıcı frekansı
tasiyici_frekans = 5000

# LDPC kodlama parametreleri
n = 32
d_v = 8
d_c = 16
snr = 20
H, G = make_ldpc(n, d_v, d_c, systematic=True, sparse=True)
k = G.shape[1]
# PyAudio nesnesi oluştur
p = pyaudio.PyAudio()
# Çıkış akışını aç
stream = p.open(
format=FORMAT,
channels=CHANNELS,
rate=RATE,
output=True,
frames_per_buffer=CHUNK
    )
def ses_gonder(bits):
    # Veriyi genişlet (CHUNK uzunluğunda)
    genisletilmis_veri = np.repeat(bits, CHUNK // len(bits))

    # Taşıyıcı dalga oluşturma
    t = np.arange(0, len(genisletilmis_veri)) / RATE
    tasiyici_dalga = np.sin(2 * np.pi * tasiyici_frekans * t)

    # Frekans modülasyonu
    m = tasiyici_dalga * (genisletilmis_veri * 2 - 1)
    modüle_edilmis_dalga = m * 32767  # Ses cihazına uygun aralığa getir

    # Modüle edilmiş dalgayı ses cihazına gönderme
    stream.write(modüle_edilmis_dalga.astype(np.int16).tobytes())

def onluk_binarye_cevir(onluk_sayi):
  """Verilen onluk sayıyı 16 bitlik bir binary diziye çevirir.

  Args:
      onluk_sayi: Dönüştürülecek onluk sayı.

  Returns:
      16 bitlik binary dizi (liste).
  """
  binary_dizi = [int(bit) for bit in bin(onluk_sayi)[2:].zfill(16)]
  return binary_dizi


# Kullanım örneği:
v = np.array([1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,1], dtype=np.int16)
sayac=0
for j in range(300):
        v=onluk_binarye_cevir(j)
        sayac+=1
        ses_gonder(v)  # Veriyi ses olarak gönder      
        time.sleep(0.002)
# Akışı kapat
stream.stop_stream()
stream.close()
p.terminate()

ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave


In [170]:
onluk_binarye_cevir(8)

[0, 0, 0, 0, 1, 0, 0, 0]

print(len(sound_bits))


>>> import numpy as np
>>> from pyldpc import make_ldpc, encode, decode, get_message
>>> n = 32
>>> d_v = 4
>>> d_c = 8
>>> snr = 1000
>>> H, G = make_ldpc(n, d_v, d_c, systematic=True, sparse=True)
>>> k = G.shape[1]
>>> v = np.random.randint(2, size=k)
>>> y = encode(G, v, snr)
>>> d = decode(H, y, snr)
>>> x = get_message(G, d)
>>> assert abs(x - v).sum() == 0

print(len(y))

print(len(v))

d = decode(H, y, 20)
x = get_message(G, d)
x


print(len(y))

y

aci = np.arcsin(0.5)  

In [19]:
modüle_edilmis_dalga

array([    -0.        , -21417.70013415, -32418.20922816, ...,
       -25324.60528974,  -5574.95445348,  16886.25575742])

In [20]:
m2=modüle_edilmis_dalga/32767

In [21]:
m2

array([-0.        , -0.65363628, -0.98935543, ..., -0.77286921,
       -0.1701393 ,  0.51534336])

In [22]:
t = np.arange(0, 2048) / RATE
tasiyici_dalga = np.sin(2 * np.pi * 5000 * t)
tasiyici_dalga=np.where(tasiyici_dalga==0,1e-10,tasiyici_dalga)




In [26]:
genis_veri=(m2/tasiyici_dalga +1)/2
genis_veri=np.where(genis_veri <=0,-1,genis_veri)


In [30]:
a=al(genis_veri)

a


array([1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [32]:
def al(data):
	n = 32
	d_v = 4
	d_c = 8
	snr = 20
	H, G = make_ldpc(n, d_v, d_c, systematic=True, sparse=True)
	gruplar = [data[i:i+64] for i in range(0, len(data), 64)]
	ana_ort=np.abs(np.mean(data))
	ortalamalar =[]
	
	for grup in gruplar:
		ortalama=np.mean(grup)
		if ortalama <=0:
			ortalamalar.append(ortalama)
		else:
			ortalamalar.append(ortalama)
	ortalamalar=np.array(ortalamalar)	
	#print(ortalamalar[0])	
	d = decode(H, ortalamalar, snr)
	x=get_message(G, d)
			
	return x

In [6]:

bits = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,1], dtype=np.int16)

In [9]:

# Veriyi genişlet (CHUNK uzunluğunda)
genisletilmis_veri = np.repeat(bits, CHUNK // len(bits))

# Taşıyıcı dalga oluşturma
t = np.arange(0, len(genisletilmis_veri)) / RATE
tasiyici_dalga = np.sin(2 * np.pi * tasiyici_frekans * t)

# Frekans modülasyonu
m = tasiyici_dalga * (genisletilmis_veri * 2 - 1)
modüle_edilmis_dalga = m   # Ses cihazına uygun aralığa getir



In [10]:
modüle_edilmis_dalga

array([-0.00000000e+00, -6.53636284e-01, -9.89355426e-01, -8.43869563e-01,
       -2.87940450e-01,  4.08037812e-01,  9.05553689e-01,  9.62624247e-01,
        5.51491374e-01, -1.27877162e-01, -7.45048505e-01, -9.99841415e-01,
       -7.68329122e-01, -1.63115114e-01,  5.21435203e-01,  9.52368648e-01,
        9.20086805e-01,  4.40290991e-01, -2.53654584e-01, -8.24227050e-01,
       -9.93910037e-01, -6.80172738e-01, -3.56114331e-02,  6.26270644e-01,
        9.83545741e-01,  8.62441563e-01,  3.21861042e-01, -3.75267005e-01,
       -8.89871809e-01, -9.71658683e-01, -5.80847936e-01,  9.24769870e-02,
        7.20822737e-01,  9.98573040e-01,  7.90635054e-01,  1.98146143e-01,
       -4.90717552e-01, -9.40904898e-01, -9.33452720e-01, -4.71985628e-01,
        2.19046937e-01,  8.03538941e-01,  9.97203797e-01,  7.05846340e-01,
        7.11776904e-02, -5.98110530e-01, -9.76488354e-01, -8.79919490e-01,
       -3.55373328e-01,  3.42020143e-01,  8.73061058e-01,  9.79460496e-01,
        6.09467648e-01, -